version: 2.1
jobs:
  build:
    working_directory: ~/portfolio
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-project
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # run linter
          name: lint
          command: yarn lint
      - run: # run tests
          name: test
          command: yarn test
      - run: # run build
          name: build
          command: yarn build
      - run: # run deploy
          name: deploy
          command: yarn deploy
