version: 2

aliases:
  - &docker
    - image: circleci/openjdk:8-jdk-node-browsers

  # SETUP aliases
  - &restore_yarn_cache
    - restore_cache: # 1st step-type
        name: Restoring cache
        key: dependency-cache-{{ checksum "yarn.lock" }}

  - &create_yarn_dependencies
    - run: # 2nd step-type
        name: Installing dependencies
        command: yarn install

  - &save_yarn_cache
    - save_cache: # 3rd step-type
        name: Saving cache
        key: dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - ./node_modules

  # LINT aliases
  - &run_lint
    - run:
        name: Running linter
        command: yarn run lint

  # TEST aliases
  - &run_tests
      - run:
          name: Running tests
          command: yarn run test



jobs:
  setup: # ----- SETUP JOB -----
    docker: *docker
    working_directory: ~/project

    steps:
      - checkout
      - *restore_yarn_cache
      - *create_yarn_dependencies
      - *save_yarn_cache


  lint: # ----- LINT JOB -----
    docker: *docker

    steps:
      - *run_lint

  test: # ----- TEST JOB -----
    docker: *docker

    steps:
      - *run_tests

workflows:
  version: 2
  stable:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup

