version: 2

jobs:
  build_app: # ----- job name -----
    docker:
      - image: circleci/node:8
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache: # 1st step-type
          name: restoring cache
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run: # 2nd step-type
          name: installing dependencies
          command: yarn install

      - save_cache: # 3rd step-type
          name: saving cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: # 4th step-type
          name: running linter
          command: yarn run lint

      - run: # 5th step-type
          name: running tests
          command: yarn run test

      - run: # 6th step-type
          name: running build
          command: yarn run build
          when: always

  deploy_app_in_GhPages: # ----- job name -----
    docker:
      - image: circleci/node:8
    working_directory: ~/project

    steps:
        - run: # 1st step-type
            name: running deploy
            command: yarn run deploy
    requires:
      - build_app

