version: 2

jobs:
  build: # ----- job name -----
    docker:
      - image: circleci/node:8
    working_directory: ~/project

    steps:
      - checkout

      - restore_cache: # 1st step-type
          name: Restoring cache
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run: # 2nd step-type
          name: Installing dependencies
          command: yarn install

      - save_cache: # 3rd step-type
          name: Saving cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: # 4th step-type
          name: Running linter
          command: yarn run lint

      - run: # 5th step-type
          name: Running tests
          command: yarn run test

      - run: # 6th step-type
          name: Running build
          command: yarn run build
          when: always

      - run: # 7st step-type
          name: Running deploy
          command: yarn run deploy

